import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from "react";
import Layout from '@/components/layouts/Layout';


export default function Courses() {
  
  return (
    <>
      <Head>
        <title>Progobees | Courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

      </Layout>
    </>
  )
}
